version: "3"

services:
  directus:
    image: directus/directus:11.7.2
    ports:
      - 8055:8055
    volumes:
      - directus_uploads:/directus/uploads
      - directus_database:/directus/database
      - ./directus_extensions:/directus/extensions
    environment:
      SECRET: ${DIRECTUS_SECRET}

      DB_CLIENT: "pg"
      DB_HOST: ${DATABASE_HOST}
      DB_PORT: "5432"
      DB_DATABASE: ${DATABASE_NAME}
      DB_USER: "directus"
      DB_PASSWORD: ${DATABASE_PASSWORD}

      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      REDIS: ${REDIS}

      CONTENT_SECURITY_POLICY_DIRECTIVES__SCRIPT_SRC: "array:'self' data:"

      WEBSOCKETS_ENABLED: true

      # After first successful login, remove the admin email/password env. variables below
      # as these will now be stored in the database.
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "admin"
volumes:
  directus_uploads:
  directus_database:
