version: "3"

services:
  directus:
    image: directus/directus:11.7.2
    ports:
      - 8055:8055
    volumes:
      - directus_uploads:/directus/uploads
      - directus_database:/directus/database
      - ./directus_extensions:/directus/extensions
    environment:
      SECRET: ${DIRECTUS_SECRET}
      DB_CLIENT: "pg"
      DB_HOST: ${DATABASE_HOST}
      DB_PORT: "5432"
      DB_DATABASE: ${DATABASE_NAME}
      DB_USER: "directus"
      DB_PASSWORD: ${DATABASE_PASSWORD}
      EXTENSIONS_AUTO_RELOAD: true

      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      REDIS: ${REDIS}

      CONTENT_SECURITY_POLICY_DIRECTIVES__SCRIPT_SRC: "array:'self' data:"
      WEBSOCKETS_ENABLED: true

      # CORS: Only allow your frontend(s) and allow credentials
      CORS_ENABLED: "true"
      CORS_ORIGIN: "http://127.0.0.1:3000,http://localhost:3000"
      CORS_METHODS: "GET,POST,PATCH,PUT,DELETE,OPTIONS"
      CORS_ALLOWED_HEADERS: "Content-Type,Authorization,X-Requested-With"
      CORS_CREDENTIALS: "true"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "admin"

    labels:
      - traefik.http.middlewares.directus-cors.headers.accesscontrolallowmethods=GET,POST,OPTIONS,PUT,PATCH,DELETE
      - traefik.http.middlewares.directus-cors.headers.accesscontrolalloworiginlist=http://127.0.0.1:3000,http://localhost:3000
      - traefik.http.middlewares.directus-cors.headers.accesscontrolallowheaders=Origin,Content-Type,Accept,Authorization
      - traefik.http.middlewares.directus-cors.headers.accesscontrolallowcredentials=true
      - traefik.http.routers.directus.middlewares=directus-cors@docker

volumes:
  directus_uploads:
  directus_database:
